### PR TITLE
laravel 6 support

### PR DESCRIPTION
**Pull request by christopherokonkwo**
Laravel 6 compatible

### CODE REVIEW

**Comment by bstoy** [comment]
That would be great, how about that PR?

**Comment by serin-design** [comment]
Yes please merge this PR in ASAP as this is blocking me from upgrading!

**Comment by uacode** [comment]
UP

**Comment by Briareos17** [comment]
UP, really need this to support Laravel 6.

**Comment by Briareos17** [comment]
Nice, Yanks a lot!

**Pull request merged**
