### PR TITLE
Added support for laravel 5.4

### PR DESCRIPTION
**Pull request by BirdyUK**
removed share() method and replaced with singleton as per laravel 5.4^.

### CODE REVIEW

**Comment by robincsamuel** [comment]
Please merge

**Comment by rogerraa** [comment]
Any way this could be merged please?

**Comment by bkilshaw** [comment]
Would appreciate if this could be merged..!

**Comment by Torann** [comment]
Sorry for the delay. I've moved to using https://github.com/Torann/meta-tags for my projects now

**Pull request merged**
